
import { 
  LayoutDashboard, ShoppingCart, Package, Users, Settings, 
  LogOut, Plus, Trash2, Search, BarChart3, Receipt, CreditCard, 
  UserCheck, AlertTriangle, Sparkles, TrendingUp, History, RotateCcw,
  HelpCircle, Printer, CheckCircle, Download, Store, Filter, X, Bell, Info,
  Menu, ChevronLeft, ChevronRight, Split, Wallet, List, PlusCircle, Banknote, Smartphone,
  Calendar, Clock, FileText, DollarSign, Pause, Play, Clipboard, User, Activity,
  Calculator, Wifi, WifiOff, FileDown, Eye, ArrowRight, CheckSquare, XSquare, PiggyBank, File, Percent, Tag
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  POS: ShoppingCart,
  Inventory: Package,
  Users: Users,
  Settings: Settings,
  Logout: LogOut,
  Add: Plus,
  Plus: Plus,
  Delete: Trash2,
  Search: Search,
  Reports: BarChart3,
  Receipt: Receipt,
  Card: CreditCard,
  CreditCard: CreditCard,
  UserCheck: UserCheck,
  Alert: AlertTriangle,
  AI: Sparkles,
  Sparkles: Sparkles,
  Trend: TrendingUp,
  History: History,
  Refund: RotateCcw,
  RotateCcw: RotateCcw,
  Help: HelpCircle,
  Printer: Printer,
  Check: CheckCircle,
  CheckCircle: CheckCircle,
  Download: Download,
  Store: Store,
  Filter: Filter,
  Close: X,
  Bell: Bell,
  Info: Info,
  Menu: Menu,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  Split: Split,
  Wallet: Wallet,
  List: List,
  PlusCircle: PlusCircle,
  Banknote: Banknote,
  Terminal: Smartphone,
  Smartphone: Smartphone,
  Calendar: Calendar,
  Clock: Clock,
  File: FileText,
  FileText: FileText,
  Dollar: DollarSign,
  Pause: Pause,
  Play: Play,
  Clipboard: Clipboard,
  User: User,
  Activity: Activity,
  Calculator: Calculator,
  Wifi: Wifi,
  WifiOff: WifiOff,
  FileDown: FileDown,
  Eye: Eye,
  ArrowRight: ArrowRight,
  CheckSquare: CheckSquare,
  XSquare: XSquare,
  PiggyBank: PiggyBank,
  Expenses: DollarSign,
  Deposit: PiggyBank,
  Percent: Percent,
  Tag: Tag
};