import {
  LayoutDashboard,
  ShoppingCart,
  Package,
  Users,
  Settings,
  LogOut,
  Plus,
  Trash2,
  Search,
  ChartNoAxesColumn,
  Receipt,
  CreditCard,
  UserCheck,
  TriangleAlert,
  Sparkles,
  TrendingUp,
  History,
  RotateCcw,
  CircleHelp,
  Printer,
  CircleCheck,
  Download,
  Store,
  Filter,
  X,
  Bell,
  Info,
  Menu,
  ChevronLeft,
  ChevronRight,
  Split,
  Wallet,
  List,
  CirclePlus,
  Banknote,
  Smartphone,
  Calendar,
  Clock,
  FileText,
  DollarSign,
  Pause,
  Play,
  Clipboard,
  User,
  Activity,
  Calculator,
  Wifi,
  WifiOff,
  FileDown,
  Eye,
  ArrowRight,
  SquareCheck,
  SquareX,
  PiggyBank,
  File,
  Percent,
  Tag,
  Upload,
  Globe,
  Monitor,
  MapPin,
  Shield,
  Lock,
  Unlock,
  CloudDownload,
  Key,
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  POS: ShoppingCart,
  ShoppingCart: ShoppingCart,
  Inventory: Package,
  Users: Users,
  Settings: Settings,
  Logout: LogOut,
  Add: Plus,
  Plus: Plus,
  Delete: Trash2,
  Search: Search,
  Reports: ChartNoAxesColumn,
  Receipt: Receipt,
  Card: CreditCard,
  CreditCard: CreditCard,
  UserCheck: UserCheck,
  Alert: TriangleAlert,
  AI: Sparkles,
  Sparkles: Sparkles,
  Trend: TrendingUp,
  History: History,
  Refund: RotateCcw,
  RotateCcw: RotateCcw,
  Help: CircleHelp,
  Printer: Printer,
  Check: CircleCheck,
  CheckCircle: CircleCheck,
  Download: Download,
  Store: Store,
  Filter: Filter,
  Close: X,
  Bell: Bell,
  Info: Info,
  Menu: Menu,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  Split: Split,
  Wallet: Wallet,
  List: List,
  PlusCircle: CirclePlus,
  Banknote: Banknote,
  Terminal: Smartphone,
  Smartphone: Smartphone,
  Calendar: Calendar,
  Clock: Clock,
  File: FileText,
  FileText: FileText,
  Dollar: DollarSign,
  Pause: Pause,
  Play: Play,
  Clipboard: Clipboard,
  User: User,
  Activity: Activity,
  Calculator: Calculator,
  Wifi: Wifi,
  WifiOff: WifiOff,
  FileDown: FileDown,
  Eye: Eye,
  ArrowRight: ArrowRight,
  CheckSquare: SquareCheck,
  XSquare: SquareX,
  PiggyBank: PiggyBank,
  Expenses: DollarSign,
  Deposit: PiggyBank,
  Percent: Percent,
  Tag: Tag,
  Upload: Upload,
  Globe: Globe,
  Monitor: Monitor,
  MapPin: MapPin,
  Shield: Shield,
  Lock: Lock,
  Unlock: Unlock,
  Password: Key,
  DownloadCloud: CloudDownload
};

// Debug logging for undefined icons
console.log('Debugging Icons:', Icons);
Object.entries(Icons).forEach(([key, value]) => {
  if (!value) console.error(`Icon ${key} is undefined!`);
});

